# Generated by Django 2.2.3 on 2019-07-10 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import test_alumnica.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=124)),
                ('type_moment', models.CharField(choices=[('divergente', 'divergente'), ('asimilador', 'asimilador'), ('convergente', 'convergente'), ('acomodador', 'acomodador')], max_length=10)),
                ('file_name', models.CharField(default='', max_length=150)),
                ('file', models.ImageField(upload_to=test_alumnica.models.upload_to)),
                ('folder', models.CharField(default='general', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionColb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=124)),
                ('ranking', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestColb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_obs', models.PositiveSmallIntegerField(default=0)),
                ('axis_abst', models.PositiveSmallIntegerField(default=0)),
                ('axis_exp_act', models.PositiveSmallIntegerField(default=0)),
                ('axis_exp_con', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_alumnica.QuestionColb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_alumnica.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='TestCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affi_divergente', models.PositiveSmallIntegerField(default=0)),
                ('affi_asimilador', models.PositiveSmallIntegerField(default=0)),
                ('affi_convergente', models.PositiveSmallIntegerField(default=0)),
                ('affi_acomodador', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_alumnica.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='ParCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='¿Con cuál te identificas más?', max_length=124)),
                ('type_moment_selected', models.CharField(choices=[('divergente', 'divergente'), ('asimilador', 'asimilador'), ('convergente', 'convergente'), ('acomodador', 'acomodador')], max_length=10)),
                ('option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_uno', to='test_alumnica.OptionCard')),
                ('option_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_dos', to='test_alumnica.OptionCard')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_alumnica.TestCard')),
            ],
        ),
        migrations.CreateModel(
            name='OptionColb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('axis', models.CharField(choices=[('obs', 'observacion'), ('abst', 'abstraccion'), ('exp_act', 'exp_activa'), ('exp_con', 'exp_concreta')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_alumnica.QuestionColb')),
            ],
        ),
    ]
