# Generated by Django 2.2.3 on 2019-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_alumnica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioncard',
            name='type_moment',
            field=models.CharField(choices=[('divergente', 'divergente'), ('asimilador', 'asimilador'), ('convergente', 'convergente'), ('acomodador', 'acomodador')], max_length=12),
        ),
    ]
