# Generated by Django 2.2.3 on 2019-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_alumnica', '0002_auto_20190711_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcard',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='parcard',
            name='option_2',
        ),
        migrations.AddField(
            model_name='parcard',
            name='options',
            field=models.ManyToManyField(to='test_alumnica.OptionCard'),
        ),
    ]
