# Generated by Django 2.2.3 on 2019-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_alumnica', '0004_testcard_id_last_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncard',
            name='img_url',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
