# Generated by Django 2.2.3 on 2019-07-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_alumnica', '0005_optioncard_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcolb',
            old_name='axis_abst',
            new_name='affi_acomodador',
        ),
        migrations.RenameField(
            model_name='testcolb',
            old_name='axis_exp_act',
            new_name='affi_asimilador',
        ),
        migrations.RenameField(
            model_name='testcolb',
            old_name='axis_exp_con',
            new_name='affi_convergente',
        ),
        migrations.RenameField(
            model_name='testcolb',
            old_name='axis_obs',
            new_name='affi_divergente',
        ),
        migrations.AddField(
            model_name='questioncolb',
            name='options',
            field=models.ManyToManyField(to='test_alumnica.OptionCard'),
        ),
        migrations.DeleteModel(
            name='OptionColb',
        ),
    ]
